default: true,
fenced-code-language: false
heading-style:
  style: "atx"
line-length: false
single-h1:
  front_matter_title: "Title"
no-bare-urls: false
no-inline-html: false
ul-style:
  style: "dash"
ol-prefix:
  style: "ordered"
code-fence-style:
  style: "backtick"
